[package]
name = "python-type-check"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo"] }
colored = "3.0.0"
env_logger = "0.11.8"
log = "0.4.27"
tree-sitter = "0.25.6"
tree-sitter-python = "0.23.6"
